<hr style="border: solid #CCC 1px; border-width: 1px 0px 0px 0px;"/>
<p align="center">
<a href="https://www.facebook.com/harmonydesignsinc"><img style="margin:5px 10px 1px; width:25px; height:25px; background:url(/new-images/sn_img_new.jpg) 0 0;" alt=“Facebook” src="/new-images/img_trans.gif"></a>
<a href="https://twitter.com/harmonydesigns"><img style="margin:5px 10px 1px; width:25px; height:25px; background:url(/new-images/sn_img_new.jpg) -33px 0;" alt=“Twitter” src="/new-images/img_trans.gif"></a>
<a href="http://www.pinterest.com/harmonydesigns2/"><img style="margin:5px 10px 1px; width:25px; height:25px; background:url(/new-images/sn_img_new.jpg) -67px 0;" alt=“Pinterest” src="/new-images/img_trans.gif"></a>
<a href="http://followgram.me/_harmonydesigns_"><img style="margin:5px 10px 1px; width:25px; height:25px; background:url(/new-images/sn_img_new.jpg) -100px 0;" alt=“Instagram” src="/new-images/img_trans.gif"></a>
</p>
<div>
<div class="clear"></div>
<hr style="border: solid #CCC 1px; border-width: 1px 0px 0px 0px;"/>
<table align="center" width="100%" style="" border=0>
    <tr>
      <td valign="top" rowspan="1" style="width: 150px;"> 
	    <p class="bold">Members:</p>
	    <p style="text-align:left; font-size:10px; padding-bottom:7px;">Fair Labor Association<br />
	    Museum Store Association</p>
	  <img src="/images-shared/MSA_logo.gif" width="102" height="100" alt="Museum Store Association Affiliate Logo" />
      </td>
      <td align="center" valign="top" colspan=1 style="height: 100px !important;">
	    <p class="center" id="linkBar" style="padding-bottom: 10px;"><a href="/index.php">Home</a> | <a href="/info/sitemap.php">Sitemap</a> | <a href="/info/about.php">About
      Us</a> | <a href="/info/contact_us.php">Contact Us</a> | <a href="/info/faq.php">Ordering Info</a> | <a href="/info/privacy.php">Privacy</a> |  <a href="/info/security.php">Security</a></p>
		<p class="types" style=""> 
		  Personalized Gifts &#8226; Museum Store Products &bull; Recognition Gifts
		  <br/>
		  Education &amp; Alumni Gifts &#8226; Wedding Favors &bull; Memorial Bookmarks</p>

		  <br/>


		<p style="text-align:center; vertical-align:bottom;"> 
		  Harmony Designs, Inc. &bull; 129 East Harmony Road, West Grove, PA 19390<br/>
		  Toll Free:&nbsp;888.293.1109 &bull; Fax:&nbsp;610.869.7415 <br/>
		  Email: <a href="mailto:info@harmonydesigns.com?subject=Customer Inquiry">info@harmonydesigns.com</a>
		</p>
		<br/>

		<p  style="text-align:center; font-size:10px;"> Copyright &copy; 1992-<?= date('Y'); ?> Harmony Designs, Inc. &bull; All rights reserved &bull; 
		<a href='/products/madeinusa'>Products made in USA</a>
		</p>
      </td>
      <td align="center" valign="top" rowspan="1" style="width: 150px;">


      
	<a name="trustlink" href="http://secure.trust-guard.com/security/6480" rel="nofollow" target="_blank" onclick="var nonwin=navigator.appName!='Microsoft Internet Explorer'?'yes':'no'; window.open(this.href.replace(/https?/, 'https'),'welcome','location='+nonwin+',scrollbars=yes,width=517,height='+screen.availHeight+',menubar=no,toolbar=no'); return false;" oncontextmenu="var d = new Date(); alert('Copying Prohibited by Law - This image and all included logos are copyrighted by trust-guard \251 '+d.getFullYear()+'.'); return false;"><img name="trustseal" alt="Security Seals" style="border: 0;" src="//dw26xg4lubooo.cloudfront.net/seals/logo/6480-lg.gif" /></a>	

	<!-- <a name="trustlink" href="http://secure.trust-guard.com/certificates/6480" target="_blank" onclick="var nonwin=navigator.appName!='Microsoft Internet Explorer'?'yes':'no'; window.open(this.href.replace('http', 'https'),'welcome','location='+nonwin+',scrollbars=yes,width=517,height='+screen.availHeight+',menubar=no,toolbar=no'); return false;" oncontextmenu="var d = new Date(); alert('Copying Prohibited by Law - This image and all included logos are copyrighted by trust-guard \251 '+d.getFullYear()+'.'); return false;"><img name="trustseal" alt="Security Seal" style="border: 0;" src="https://c674753.ssl.cf2.rackcdn.com/security-6480-mini-white.gif" /></a> -->





          <!-- START SCANALERT CODE -->
	  <!--
	  	<a target="_blank" href="https://www.scanalert.com/RatingVerify?ref=www.harmonydesigns.com"><img src="https://images.scanalert.com/meter/www.harmonydesigns.com/12.gif" width="115" height="32" border="0" id="mcafee_img" alt="HACKER SAFE certified sites prevent over 99.9% of hacker crime."/></a>
	-->

		<div class="AuthorizeNetSeal" style=""> 
			<a href="//verify.authorize.net/anetseal/?pid=722e3bdb-66a0-43c3-8bd6-aea4345f2ee2&amp;rurl=http://<?= $_SERVER['HTTP_HOST'] ?>" onclick="window.open('//verify.authorize.net/anetseal/?pid=722e3bdb-66a0-43c3-8bd6-aea4345f2ee2&amp;rurl=http://<?= $_SERVER['HTTP_HOST'] ?>','AuthorizeNetVerification','width=600,height=430,dependent=yes,resizable=yes,scrollbars=yes,menubar=no,toolbar=no,status=no,directories=no,location=yes'); return false;" target="_blank">
				<img src="//verify.authorize.net/anetseal/images/secure90x72.gif" id="authnet_img" alt="Authorize.Net Merchant - Click to Verify" height="72" width="90" border="0">
			</a>
		</div>
		<div class="" align="center">
			<? if(!empty($_SERVER['HTTPS'])) { ?>
			<SCRIPT LANGUAGE="JavaScript"  TYPE="text/javascript" SRC="//smarticon.geotrust.com/si.js"></SCRIPT>
			<? } ?>
		</div>
	  </td>
    </tr>
  </table>
  <div class="clear"></div>
</div>

<script type="text/javascript" language="javascript">llactid=22862</script>

<!-- LeadLander code follows-->

<script type="text/javascript" language="javascript" src="https://trackalyzer.com/trackalyze_secure.js"></script> 

<!-- AdRoll code follows-->

<script type="text/javascript">
// addroll script
adroll_adv_id = "A6SOTDGIHZA6DHI3ZIHXRI";
adroll_pix_id = "EJGVZL6Z35B75B3WJUDQSA";
(function () {
var oldonload = window.onload;
window.onload = function(){
   __adroll_loaded=true;
   var scr = document.createElement("script");
   var host = (("https:" == document.location.protocol) ? "https://s.adroll.com" : "http://a.adroll.com");
   scr.setAttribute('async', 'true');
   scr.type = "text/javascript";
   scr.src = host + "/j/roundtrip.js";
   ((document.getElementsByTagName('head') || [null])[0] ||
    document.getElementsByTagName('script')[0].parentNode).appendChild(scr);
   if(oldonload){oldonload()}};
}());
</script>

