<hr />
	<p class="center" id="linkBar">
		<a href="/index.php">Home</a> |
		<a href="/product/browse.php?browseNode=1&amp;resultOffset=1">Stamp Subjects</a> |
		<a href="/info/submission.php">Use Your Art</a> |
		<a href="/info/quantityPricing.php">Pricing</a> |
		<a href="/info/about-us.php">About Harmony Designs</a> |
		<a href="/other/links.php">Links</a> |
		<a href="/cart/display.php">Shopping Cart</a> |
		<a href="/info/privacy.php">Privacy Policy</a> |
		<a href="/custserv/index.php">Your Account</a> |
		<a href="/info/sitemap.php">Site Map</a>
	</p>
	<table align="center">
		<tr>
			<td align="right" rowspan="2" valign="middle">
				<img src="/new-images/nav-logo.gif" width="98" height="62" alt="Harmony Designs Logo" /> <p>
				<!-- START SCANALERT CODE -->
	<a target="_blank" href="https://www.scanalert.com/RatingVerify?ref=www.harmonydesigns.com"><img width="115" height="32" border="0" src="//images.scanalert.com/meter/www.harmonydesigns.com/12.gif" alt="HACKER SAFE certified sites prevent over 99.9% of hacker crime." oncontextmenu="alert('Copying Prohibited by Law - HACKER SAFE is a Trademark of ScanAlert'); return false;"></a>	<!-- END SCANALERT CODE -->
			</td>
			<td align="center" width="390" valign="middle">
				<p class="contact">
					129 East Harmony Road, West Grove, PA 19390
					<br />
					Sales:&nbsp;(888)&nbsp;293-1109&nbsp;&#8226;&nbsp;Other&nbsp;Inquiries:&nbsp;(610)&nbsp;869-4234
					<br />
					Fax:&nbsp;(610)&nbsp;869-7415&nbsp;&#8226;&nbsp;E-Mail&nbsp;(sales):&nbsp;<a href="mailto:info@harmonydesigns.com">info@harmonydesigns.com</a>
					<br />
					<span id="siteComments">
						Website Comments:&nbsp;<a href="mailto:webmaster@harmonydesigns.com">webmaster@harmonydesigns.com</a>
					</span>
				</p>
				<p class="copyright">
					Copyright &copy; 1992-2008 Harmony Designs, Inc. All rights reserved 
				</p>
			</td>
			<td align="left" rowspan="2"valign="middle">
				<img src="/new-images/MSA_logo.gif" width="102" height="100" alt="Museum Store Association Affiliate Logo" /> 
			</td>
			<td>
			<div class="AuthorizeNetSeal" style="float: right;"> 
	<script type="text/javascript" language="javascript">var ANS_customer_id="722e3bdb-66a0-43c3-8bd6-aea4345f2ee2";</script> 
	<script type="text/javascript" language="javascript" src="http://VERIFY.AUTHORIZE.NET/anetseal/seal.js" ></script> 
	<a href="http://www.authorize.net/" id="AuthorizeNetText" target="_blank">Credit Card Processing</a> 
</div>
			</td>
		</tr>
		<tr>
			<td align="center" width="390">
				<img src="/new-images/gift-tag.gif" width="344" height="14" alt="Gifts, Museum Store Products, Promotional Items" /> 
			</td>
			
		</tr>
	</table>
<!-- Frameset Breakout -->
	<script src="/breakout.js" language="JavaScript" type="text/javascript">
	</script>
<!-- Frameset Breakout -->
<!-- (c) 2006. Authorize.Net is a registered trademark of Lightbridge, Inc. --> 

