<table id="five_step_banner">
<tr>
	<th colspan=4 id="five_step_title">
		<h3>Build Your Custom Personalized Gifts</h3>
	</th>
</tr>
<tr>
	<td colspan=4>
		bookmarks &bull;
		mugs &bull;
		magnets &bull;
		paperweights &bull;
		keychains &bull;
		custom rulers &bull;
		<a href="/details">and more...</a>
	</td>
</tr>
<tr id="five_step_row">
	<td id="five_step_step1" class="five_step_step">
		<div class="five_step_step_num">1</div>
		<div class="five_step_step_title">	
			<a href="/">Select Your Product</a>
		</div>
		<div class="five_step_step_link">
			<a href="/">Change Product</a>
		</div>
	</td>
	<td id="five_step_step2" class="five_step_step">
		<div class="five_step_step_num">2</div>
		<div class="five_step_step_title">
			<a href="/">Select Your Image</a>
		</div>
	</td>
	<td id="five_step_step3" class="five_step_step">
		<div class="five_step_step_num">3</div>
		<div class="five_step_step_title">
			<a href="/">Customize Your Product</a>
		</div>
	</td>
	<td id="five_step_step4" class="five_step_step">
		<div class="five_step_step_num">4</div>
		<div class="five_step_step_title">
			<a href="/">Checkout</a>
		</div>
	</td>
</tr>
</table>
