<!-- Start LiveChatNow! button code -->
<script type="text/javascript">
function _lcn_isSecure(){ return location.href.match(/^https/i) == "https";}
if(typeof(LCNObj) == 'undefined') {var LCNObj = new Object();}
if(_lcn_isSecure()){LCNObj.url1 = "https://chat.livechatnow.com/";}else{LCNObj.url1 = "http://chat.livechatnow.com/";}
LCNObj.query = "&img=i&group=General&skin=&survey=&survey_ec=&survey_lm=&rule=&name=&email=&track=";
LCNObj.open = LCNObj.url1 + "js/enter.php?cid=17870" + LCNObj.query;LCNObj.image = LCNObj.url1 + "img/img.php?id=17870" + LCNObj.query + "&t=" + (new Date()).getTime();
function _cln_enter(){ window.open(LCNObj.open, '_chat_17870', 'resizable=yes,menubar=no,scrollbars=yes, width=500, height=500'); return false;}
document.write("<a href='"+LCNObj.open+"' onclick='return _cln_enter();'><img src='"+LCNObj.image+"' border='0' /></a>");
</script>
<!--Powered by <a href="http://www.livechatnow.com/" target="_blank">LiveChatNow!</a>-->
<!-- End LiveChatNow! button code -->

