<?php
	include ('sidebarSearch2.inc');
?>
<!--Begin Subject/Product Navigation-->
<div class="toggle-button"><a href="#" class="nav"><img src="/images-shared/buttonProductChecked.gif" alt="Shop by Product" width="87" height="21" border="0"></a></div>
<div class="toggle-button"><a href="#" class="nav"><img src="/images-shared/buttonSubject.gif" alt="Shop by Subject" width="88" height="21" border="0"></a></div>
<?php
	include ('products.inc');
?>
<!--End Subject/Product Navigation-->