		<div id="productColumn">
			<h6 class="center">
				Use stamps or images on these items
			</h6>
			<p class="note">(click images for information.)</p>
			<p class="product">
				<a href="/details/bookmark.php?start_over=1"><img src="/new-images/Large-Thumbnails/Bookmark.gif" alt="bookmark" width="65" height="64" border="0" /></a>
				<br>
				<a href="/details/bookmark.php?start_over=1">Bookmarks</a>
			</p>
			<p class="product">
				<a href="/details/framedstamp.php?start_over=1"><img src="/new-images/Large-Thumbnails/Framed-Stamp.gif" alt="framed stamp" width="65" height="64" border="0" />
				<br>
				<a href="/details/framedstamp.php?start_over=1">Framed Stamps</a>
			</p>
			<p class="product">
				<a href="/details/keychain.php?start_over=1"><img src="/new-images/Large-Thumbnails/Keychains.gif" alt="keychains" width="65" height="64" border="0" /></a>
				<br>
				<a href="/details/keychain.php?start_over=1">Keychains</a>
			</p>
			<p class="product">
				<a href="/details/bagtag.php?start_over=1"><img src="/new-images/Large-Thumbnails/Bag-Tag.gif" alt="bag tag" width="65" height="64" border="0" /></a>
				<br>
				<a href="/details/bagtag.php?start_over=1">Luggage Tags</a>
			</p>
			<p class="product">
				<a href="/details/magnet.php?start_over=1"><img src="/new-images/Large-Thumbnails/NMM-GrandmaMoses-tiny.gif" alt="Magnets" width="65" height="64" border="0" /></a>
				<br>
				<a href="/details/magnet.php?start_over=1">Magnets</a>
			</p>
			<p class="product">
				<a href="/details/mug.php?start_over=1"><img src="/new-images/Large-Thumbnails/coffee-mug.jpg" alt="coffee mug" width="65" height="64" border="0" /></a>
				<br>
				<a href="/details/mug.php?start_over=1">Mugs</a>
			</p>
			<p class="product">
				<a href="/details/ornament.php?start_over=1"><img src="/new-images/Large-Thumbnails/Ornament.gif" alt="ornament" width="65" height="64" border="0" /></a>
				<br>
				<a href="/details/ornament.php?start_over=1">Ornaments</a>
			</p>
			<p class="product">
				<a href="/details/paperweight.php?start_over=1"><img src="/new-images/Large-Thumbnails/Pageweights.gif" alt="pageweights" width="65" height="64" border="0" /></a>
				<br>
				<a href="/details/paperweight.php?start_over=1">Paperweights</a>
			</p>
			<p class="product">
				<a href="/details/pin.php?start_over=1"><img src="/new-images/Large-Thumbnails/pins.gif" alt="pins" width="65" height="64" border="0" /></a>
				<br>
				<a href="/details/pin.php?start_over=1">Pins &amp; Tie&nbsp;Tacks</a>
			</p>
			<p class="product">
				<a href="/details/postcard.php?start_over=1"><img src="/new-images/Large-Thumbnails/PC.jpg" alt="postcard" width="65" height="64" border="0" /></a>
				<br>
				<a href="/details/postcard.php?start_over=1">Postcards</a>
			</p>
			<p class="product">
				<a href="/details/poster.php?start_over=1"><img src="/new-images/Large-Thumbnails/Poster.jpg" alt="poster" width="65" height="64" border="0" /></a>
				<br>
				<a href="/details/poster.php?start_over=1">Posters</a>
			</p>
			<p class="product">
				<a href="/details/puzzle.php?start_over=1"><img src="/new-images/Large-Thumbnails/PZ.jpg" alt="puzzle" width="65" height="64" border="0" /></a>
				<br>
				<a href="/details/puzzle.php?start_over=1">Puzzles</a>
			</p>
			<p class="product">
				<a href="/details/customruler.php?start_over=1"><img src="/new-images/Large-Thumbnails/Ruler.jpg" alt="custom ruler" width="65" height="64" border="0" /></a>
				<br>
				<a href="/details/customruler.php?start_over=1">Rulers</a>
			</p>
			<p class="product">
				<a href="/details/stamp-on-card.php?start_over=1"><img src="/new-images/Large-Thumbnails/Stamp-on-Card.gif" alt="stamp on cards" width="65" height="64" border="0" /></a>
				<br>
				<a href="/details/stamp-on-card.php?start_over=1">Stamps on Cards</a>
			</p>
			<p class="product">
				<a href="/details/totebag.php?start_over=1"><img src="/new-images/Large-Thumbnails/TB.jpg" alt="tote bags" width="65" height="64" border="0" /></a>
				<br>
				<a href="/details/totebag.php?start_over=1">Tote Bags</a>
			</p>
			<hr class="divider center" />
			<h6 class="center">
				Image Only Items
			</h6>
			<p class="note">(click images for information.)</p>
			<p class="product">
				<a href="/details/t-shirt.php?start_over=1"><img src="/new-images/Large-Thumbnails/T-Shirt.gif" alt="t-shirts" width="65" height="73" border="0"></a>
				<br>
				<a href="/details/t-shirt.php?start_over=1">T-Shirts</a>
			</p>
			<hr class="divider center" />
			<h6 class="center">
				Non-Personalized Items
			</h6>
			<p class="note">(click images for information.)</p>
			<p class="product">
				<a href="/details/charm.php?start_over=1"><img src="/new-images/Large-Thumbnails/Charm.gif" alt="bookmark" width="65" height="64" border="0"></a>
				<br>
				<a href="/details/charm.php?start_over=1">Charms</a>
			</p>
			<p class="product">
				<a href="/details/paperweightkit.php?start_over=1"><img src="/new-images/Large-Thumbnails/paperweightKits.gif" alt="paperweight kits" width="64" height="63" border="0"></a>
				<br>
				<a href="/details/paperweightkit.php?start_over=1">Paperweight Kits</a>
			</p>
			<p class="product">
				<a href="/details/ruler.php?start_over=1"><img src="/new-images/Large-Thumbnails/presidentsRuler.gif" alt="presidents rulers" width="64" height="63" border="0"></a>
				<br>
				<a href="/details/ruler.php?start_over=1">Presidents Rulers</a>
			</p>
			<p class="product">
				<a href="/details/tassel.php?start_over=1"><img src="/new-images/Large-Thumbnails/Tassels.gif" alt="bookmark tassels" width="64" height="63" border="0"></a>
				<br>
				<a href="/details/tassel.php?start_over=1">Bookmark Tassels</a>
			</p>
		</div>
