<div id="otherProductsDropdown">
	<select style="width: 100%;" onChange="var href = this.options[this.selectedIndex].value; if (href) { document.location.href = href; } ">
		<option value="">Shop By Product:</option>

		<option value=""></option>
		<option value="/details/bookmark.php">Bookmarks</option> 
		<option value="/details/paperweight.php">Glass Paperweights</option> 
		<option value="/details/mug.php">Mugs</option>
		<option value="/details/magnet.php">Magnets</option> 

		<option value=""></option>
		<option value="/details/framedstamp.php">Framed Stamps</option> 
		<option value="/details/keychain.php">Keychains</option> 
		<option value="/details/bagtag.php">Luggage Tags</option> 
		<option value="/details/ornament.php">Ornaments</option> 
		<option value="/details/pin.php">Pins and Tie Tacks</option> 
		<option value="/details/poster.php">Posters</option>
		<option value="/details/postcard.php">Postcards</option>
		<option value="/details/puzzle.php">Puzzles</option> 
		<option value="/details/customruler.php">Rulers (Custom)</option>
		<option value="/details/stamp-on-card.php">Stamps on Cards</option> 
		<option value="/details/t-shirt.php">T-Shirts</option> 
		<option value="/details/totebag.php">Tote Bags</option> 


		<option value=""></option>
		<option value="/details/tassel.php">Bookmark Tassels</option> 
		<option value="/details/paperweightkit.php">Blank Paperweight Kits</option> 
		<option value="/details/ruler.php">Presidents Rulers</option> 
		<option value="/details/charm.php">Charms</option> 
	</select>
</div>
