<div id="productList">
	<h4>Shop by Product</h4>

	<div class="productListSubheader">Popular Items:</div>
	<ul id="popularProducts">
		<li>
			<a href="/details/bookmark.php">Bookmarks</a> 
		</li>
		<li>
			<a href="/details/paperweight.php">Glass Paperweights</a> 
		</li>
	</ul>

	<div class="productListSubheader">Other Items:</div>
	<ul id="otherProducts">
		<li>
			<a href="/details/framedstamp.php">Framed Stamps</a> 
		</li>
		<li>
			<a href="/details/keychain.php">Keychains</a> 
		</li>
		<li>
			<a href="/details/bagtag.php">Luggage Tags</a> 
		</li>
		<li>
			<a href="/details/magnet.php">Magnets</a> 
		</li>
		<li>
			<a href="/details/mug.php">Mugs</a>
		</li>
		<li>
			<a href="/details/ornament.php">Ornaments</a> 
		</li>
		<li>
			<a href="/details/pin.php">Pins and Tie Tacks</a> 
		</li>
		<li>
			<a href="/details/poster.php">Posters</a>
		</li>
		<li>
			<a href="/details/postcard.php">Postcards</a>
		</li>
		<li>
			<a href="/details/puzzle.php">Puzzles</a> 
		</li>
		<li>
			<a href="/details/customruler.php">Rulers <span class="note">(Custom)</span></a>
		</li>
		<li>
			<a href="/details/stamp-on-card.php">Stamps on Cards</a> 
		</li>
		<li>
			<a href="/details/t-shirt.php">T-Shirts</a> 
		</li>
		<li>
			<a href="/details/totebag.php">Tote Bags</a> 
		</li>
	</ul>

	<div class="productListSubheader">Stock Items:</div>
	<ul id="stockProducts">
		<li>
			<a href="/details/tassel.php">Bookmark Tassels</a> 
		</li>
		<li>
			<a href="/details/paperweightkit.php">Blank Paperweight Kits</a> 
		</li>
		<li>
			<a href="/details/ruler.php">Presidents Rulers</a> 
		</li>
		<li>
			<a href="/details/charm.php">Charms</a> 
		</li>
	</ul>
</div>
