<div id="product_table">
			<h4 class="product_category_header">Most Popular Items:</h4>
			<table class="itemList" cellspacing="0">
				<tr>
					<td class="itemDisplay">
						<a href="/details/bookmark.php"><img src="/new-images/purchase-thumbnails/B.jpg" width="96" height="94" border="0" /><br /><span id="item">Bookmarks</span></a> 
					</td>
					<td class="itemDisplay">
						<a href="/details/paperweight.php"><img src="/new-images/purchase-thumbnails/paperweights.jpg" width="96" height="94" border="0" /><br /><span id="item">Glass Paperweights</span></a> 
					</td>
					<td class="itemDisplay">
						 <a href="/details/mug.php"><img src="/new-images/purchase-thumbnails/MG.jpg" width="96" height="94" border="0" /><br /><span id="item">Mugs</span></a>
 					</td>
					<td class="itemDisplay">
						<a href="/details/magnet.php"><img src="/new-images/purchase-thumbnails/NMM-GrandmaMoses-tiny.gif" width="96" height="94" border="0" /><br /><span id="item">Magnets</span></a> 
					</td>
					<td class="itemDisplay">
						<a href="/details/keychain.php"><img src="/new-images/purchase-thumbnails/keychains.jpg" width="96" height="94" border="0" /><br /><span id="item">Keychains</span></a> 
					</td>
					<td class="itemDisplay">
						<a href="/details/totebag.php"><img src="/new-images/purchase-thumbnails/Totebag-image-tiny.gif" width="96" height="106" border="0" /><br /><span id="item">Tote Bags</span></a> 
				  </td>
				</tr>
			</table>

			<h4 class="product_category_header">Stock Items:</h4>
			<table class="itemList" cellspacing="0">
			<tr>
					<td class="itemDisplay">&nbsp;
						<a href="/details/tassel.php"><img src="/new-images/purchase-thumbnails/tassels.jpg" width="96" height="94" border="0" /><br /><span id="item">Tassels</span></a> 
				    </td>
					<td class="itemDisplay">
						<a href="/details/paperweightkit.php"><img src="/new-images/purchase-thumbnails/paperweight-kit.jpg" width="96" height="94" border="0" /><br /><span id="item">Blank Paperweight Kits</span></a> 
					</td>
					<td class="itemDisplay">
						<a href="/details/ruler.php"><img src="/new-images/purchase-thumbnails/ruler.jpg" width="96" height="94" border="0" /><br /><span id="item">Presidents Rulers</span></a> 
					</td>
					<td class="itemDisplay">
						<a href="/details/charm.php"><img src="/new-images/purchase-thumbnails/Charms-group-tiny.gif" width="96" height="94" border="0" /><br /><span id="item">Charms</span></a> 
					</td>
			  </tr>
			  </table>


			<h4 class="product_category_header">All Items:</h4>
			<table class="itemList" cellspacing="0">
				<tr>
					<td class="itemDisplay">
						<a href="/details/bookmark.php"><img src="/new-images/purchase-thumbnails/B.jpg" width="96" height="94" border="0" /><br /><span id="item">Bookmarks</span></a> 
					</td>
					<td class="itemDisplay">
						<a href="/details/framedstamp.php"><img src="/new-images/purchase-thumbnails/FS.jpg" width="96" height="94" border="0" /><br /><span id="item">Framed Stamps</span></a> 
					</td>
					<td class="itemDisplay">
						<a href="/details/paperweight.php"><img src="/new-images/purchase-thumbnails/paperweights.jpg" width="96" height="94" border="0" /><br /><span id="item">Glass Paperweights</span></a> 
					</td>
					<td class="itemDisplay">
						<a href="/details/keychain.php"><img src="/new-images/purchase-thumbnails/keychains.jpg" width="96" height="94" border="0" /><br /><span id="item">Keychains</span></a> 
					</td>
					<td class="itemDisplay">
						<a href="/details/bagtag.php"><img src="/new-images/purchase-thumbnails/BT.jpg" width="96" height="94" border="0" /><br /><span id="item">Luggage Tags</span></a> 
					</td>
					<td class="itemDisplay">
						<a href="/details/magnet.php"><img src="/new-images/purchase-thumbnails/NMM-GrandmaMoses-tiny.gif" width="96" height="94" border="0" /><br /><span id="item">Magnets</span></a> 
					</td>
				</tr>
				<tr>
					<td class="itemDisplay">
						 <a href="/details/mug.php"><img src="/new-images/purchase-thumbnails/MG.jpg" width="96" height="94" border="0" /><br /><span id="item">Mugs</span></a>
 					</td>
					<td class="itemDisplay">
						<a href="/details/ornament.php"><img src="/new-images/purchase-thumbnails/ORN.jpg" width="96" height="94" border="0" /><br /><span id="item">Ornaments</span></a> 
					</td>
					<td class="itemDisplay">
						<a href="/details/postcard.php"><img src="/new-images/purchase-thumbnails/Postcard-fanned-tiny.gif" width="96" height="94" border="0" /><br /><span id="item">Postcards</span></a> 
					</td>
					<td class="itemDisplay">
						<a href="/details/poster.php"><img src="/new-images/purchase-thumbnails/PS.jpg" width="96" height="94" border="0" /><br /><span id="item">Posters</span></a> 
					</td>
					<td class="itemDisplay">
						<a href="/details/pin.php"><img src="/new-images/purchase-thumbnails/P.jpg" width="96" height="94" border="0" /><br /><span id="item">Pins or Tie Tacks</span></a> 
					</td>
					<td class="itemDisplay">
						<a href="/details/puzzle.php"><img src="/new-images/purchase-thumbnails/Puzzle-Anthony-tiny.gif" width="96" height="94" border="0" /><br /><span id="item">Puzzles</span></a> 
					</td>
				</tr>
				<tr>	
					<td class="itemDisplay">
						<a href="/details/customruler.php"><img src="/new-images/purchase-thumbnails/RL.jpg" width="96" height="94" border="0" /><br /><span id="item">Rulers <span class="note">(Custom)</span></span></a> 
					</td>
					<td class="itemDisplay">
						<a href="/details/stamp-on-card.php"><img src="/new-images/purchase-thumbnails/ST.jpg" width="96" height="94" border="0" /><br /><span id="item">Stamps on Cards</span></a> 
					</td>
					<td class="itemDisplay">
						<a href="/details/totebag.php"><img src="/new-images/purchase-thumbnails/Totebag-image-tiny.gif" width="96" height="106" border="0" /><br /><span id="item">Tote Bags</span></a> 
				  </td>
					<td class="itemDisplay">
						<a href="/details/t-shirt.php"><img src="/new-images/homepagethumbs/T-shirt-image-tiny.gif" width="96" height="106" border="0" /><br /><span id="item">T-Shirts</span></a> 
				  </td>
				</tr>
			</table>
</div>
