		<p>
			All images and stamps are available on any of the following products:
		</p>
		<p class="center">
			<a href="/details/bagspecs.lasso"><img src="/new-images/Large-Thumbnails/Bag-Tag.gif" alt="bag tag" width="65" height="64" border="0"></a>
			<br>
			<a href="/details/bagspecs.lasso">Bag Tags</a>
		</p>
		<p class="center">
			<a href="/details/bookspecs.lasso"><img src="/new-images/Large-Thumbnails/Bookmark.gif" alt="bookmark" width="65" height="64" border="0"></a>
			<br>
			<a href="/details/bookspecs.lasso">Bookmarks</a>
		</p>
		<p class="center">
			<a href="/details/FSspecs.lasso"><img src="/new-images/Large-Thumbnails/Framed-Stamp.gif" alt="framed stamp" width="65" height="64" border="0">
			<br>
			<a href="/details/FSspecs.lasso">Framed Stamps</a>
		</p>
		<p class="center">
			<a href="/details/keyspecs.lasso"><img src="/new-images/Large-Thumbnails/Keychains.gif" alt="keychains" width="65" height="64" border="0"></a>
			<br>
			<a href="/details/keyspecs.lasso">Keychains</a>
		</p>
		<p class="center">
			<a href="/details/Magnetspecs.lasso"><img src="/new-images/Large-Thumbnails/Magnets.gif" alt="Magnets" width="65" height="64" border="0"></a>
			<br>
			<a href="/details/Magnetspecs.lasso">Magnets&#8482;</a>
		</p>
		<p class="center">
			<a href="/details/Ornamentspecs.lasso"><img src="/new-images/Large-Thumbnails/Ornament.gif" alt="ornament" width="65" height="64" border="0"></a>
			<br>
			<a href="/details/Ornamentspecs.lasso">Ornaments</a>
		</p>
		<p class="center">
			<a href="/details/weightspecs.lasso"><img src="/new-images/Large-Thumbnails/Pageweights.gif" alt="pageweights" width="65" height="64" border="0"></a>
			<br>
			<a href="/details/weightspecs.lasso">Pageweights&#174;</a>
		</p>
		<p class="center">
			<a href="/details/Pinspecs.lasso"><img src="/new-images/Large-Thumbnails/pins.gif" alt="pins" width="65" height="64" border="0"></a>
			<br>
			<a href="/details/Pinspecs.lasso">Pins &amp; Tie Tacks</a>
		</p>
		<p class="center">
			<a href="/details/Stamp-on-Card-specs.lasso"><img src="/new-images/Large-Thumbnails/Stamp-on-Card.gif" alt="stamp on cards" width="65" height="64" border="0"></a>
			<br>
			<a href="/details/Stamp-on-Card-specs.lasso">Stamps on Cards</a>
		</p>
