		<h6 class="center">
			Use your art on any of these items
		</h6>
		<p class="note">(click images for information.)</p>
		<div id="productColumn">
			<p class="product">
				<a href="/details/bookmark.php"><img src="/new-images/Large-Thumbnails/Bookmark.gif" alt="bookmark" width="65" height="64" border="0"></a>
				<br>
				<a href="/details/bookmark.php">Bookmarks</a>
			</p>
			<p class="product">
				<a href="/details/keychain.php"><img src="/new-images/Large-Thumbnails/Keychains.gif" alt="keychains" width="65" height="64" border="0"></a>
				<br>
				<a href="/details/keychain.php">Keychains</a>
			</p>
			<p class="product">
				<a href="/details/bagtag.php"><img src="/new-images/Large-Thumbnails/Bag-Tag.gif" alt="bag tag" width="65" height="64" border="0"></a>
				<br>
				<a href="/details/bagtag.php">Luggage&nbsp;Tags</a>
			</p>
			<p class="product">
				<a href="/details/magnet.php"><img src="/new-images/Large-Thumbnails/Magnets.gif" alt="Magnets" width="65" height="64" border="0"></a>
				<br>
				<a href="/details/magnet.php">Magnets</a>
			</p>
			<p class="product">
				<a href="/details/mug.php"><img src="/new-images/Large-Thumbnails/coffee-mug.jpg" alt="coffee mug" width="65" height="64" border="0" /></a>
				<br>
				<a href="/details/mug.php">Mugs</a>
			</p>
			<p class="product">
				<a href="/details/ornament.php"><img src="/new-images/Large-Thumbnails/Ornament.gif" alt="ornament" width="65" height="64" border="0"></a>
				<br>
				<a href="/details/ornament.php">Ornaments</a>
			</p>
			<p class="product">
				<a href="/details/paperweight.php"><img src="/new-images/Large-Thumbnails/Pageweights.gif" alt="pageweights" width="65" height="64" border="0"></a>
				<br>
				<a href="/details/paperweight.php">Paperweights</a>
			</p>
			<p class="product">
				<a href="/details/poster.php"><img src="/new-images/Large-Thumbnails/Poster.jpg" alt="poster" width="65" height="64" border="0" /></a>
				<br>
				<a href="/details/poster.php">Posters</a>
			</p>
			<p class="product">
				<a href="/details/customruler.php"><img src="/new-images/Large-Thumbnails/Ruler.jpg" alt="custom ruler" width="65" height="64" border="0" /></a>
				<br>
				<a href="/details/customruler.php">Rulers</a>
			</p>
			<p class="product">
				<a href="/details/t-shirt.php"><img src="/new-images/Large-Thumbnails/T-Shirt.gif" alt="t-shirts" width="65" height="73" border="0"></a>
				<br>
				<a href="/details/t-shirt.php">T-Shirts</a>
			</p>
			<hr class="divider center" />
			<h6 class="center">
				Other items
			</h6>
			<p class="note">(click images for information.)</p>
			<p class="product">
				<a href="/details/charm.php"><img src="/new-images/Large-Thumbnails/Charm.gif" alt="bookmark" width="65" height="64" border="0"></a>
				<br>
				<a href="/details/charm.php">Charms</a>
			</p>
			<p class="product">
				<a href="/details/framedstamp.php"><img src="/new-images/Large-Thumbnails/Framed-Stamp.gif" alt="framed stamp" width="65" height="64" border="0" />
				<br>
				<a href="/details/framedstamp.php">Framed Stamps</a>
			</p>
			<p class="product">
				<a href="/details/poster.php"><img src="/new-images/Large-Thumbnails/paperweightKits.gif" alt="paperweight kits" width="64" height="63" border="0"></a>
				<br>
				<a href="/details/poster.php">Paperweight Kits</a>
			</p>
			<p class="product">
				<a href="/details/pin.php"><img src="/new-images/Large-Thumbnails/pins.gif" alt="pins" width="65" height="64" border="0" /></a>
				<br>
				<a href="/details/pin.php">Pins &amp; Tie Tacks</a>
			</p>
			<p class="product">
				<a href="/details/customruler.php"><img src="/new-images/Large-Thumbnails/presidentsRuler.gif" alt="presidents rulers" width="64" height="63" border="0"></a>
				<br>
				<a href="/details/customruler.php">Presidents Rulers</a>
			</p>
			<p class="product">
				<a href="/details/stamp-on-card.php"><img src="/new-images/Large-Thumbnails/Stamp-on-Card.gif" alt="stamp on cards" width="65" height="64" border="0" /></a>
				<br>
				<a href="/details/stamp-on-card.php">Stamps on Cards</a>
			</p>
			<p class="product">
				<a href="/details/tassel.php"><img src="/new-images/Large-Thumbnails/Tassels.gif" alt="bookmark tassels" width="64" height="63" border="0"></a>
				<br>
				<a href="/details/tassel.php">Bookmark Tassels</a>
			</p>
		</div>