<h4>DOs and DON'Ts for Submitting Art</h4> 
<p>
	<strong>DO</strong> send a large image. The larger the image, the better it will look when put on a gift item. A good rule of thumb is to view your image so it fills your computer screen. If it looks good at that size, it will probably work well when printed on gift items. 
</p>
<p>
	<strong>DON&#8217;T</strong> Send a file over <em>4&nbsp;Megabytes</em>. Larger images may be <a href="/info/submission2.php">sent via U.S. mail</a>.				
</p>
<p>
	<strong>DON&#8217;T</strong> use a graphic from a website. The quality of the graphics is poor compared to the images we use on the products. Here is a sample logo taken from a website:
	<br />
	While it looks pretty good here&#x2026;
	<br />
	<img src="/new-images/SampleLogo3.gif" alt="" border="0" />
	<br />
		&#x2026;a closer look shows numerous imperfections:
	<br />
	<img src="/new-images/SampleLogo2.gif" alt="" height="109" width="144" border="0" />
	<br />
	These same imperfections become very apparent when printed onto an item.
	Web sites display graphics at 72 dots per inch (dpi). Larger images, at 300 dpi, are needed for high quality printing.
</p>
<p>
	<strong>DO</strong> send image files in the following formats: JPG, GIF, PSD (PhotoShop), or PNG. For JPG files, please save at the highest quality. Images sent by eMail or U.S. Mail may also be sent in TIFF, EPS, BMP or PDF format.
</p>
